name: Validate README.md Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate README.md files
        run: |
          bash .github/scripts/validate-readme.sh | tee validation_output.txt
          exit ${PIPESTATUS[0]}

      - name: Add validation results as PR comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## :mag: README Validation Results

            ```
            $(cat validation_output.txt)
            ```