name: Validate README.md Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  validate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate README.md files
        id: validate-readme
        run: |
          bash .github/scripts/validate-readme.sh
          exit ${PIPESTATUS[0]}
        continue-on-error: true

      - name: Add validation results as PR comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          body: |
            ## :mag: README Validation Results

            ${steps.validate-readme.outputs.results}