name: Validate README.md Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Validate README.md files
        run: |
          #!/bin/bash
          
          # Function to check if a directory has a README.md file
          check_readme() {
            local dir=$1
            if [ ! -f "$dir/README.md" ]; then
              echo "❌ Error: $dir is missing README.md file"
              exit 1
            fi
          }

          # Function to check if root README.md links to directory README.md in a section heading
          check_root_links() {
            local dir=$1
            local dir_name=$(basename "$dir")
            # Look for a section heading like ### [GitHub](github/README.md)
            if ! grep -Eq "^### \[$dir_name\]\($dir/README.md\)" README.md; then
              echo "❌ Error: Root README.md is missing section heading link to $dir/README.md"
              exit 1
            fi
          }

          # Get all directories that should have README.md files
          # Exclude .git, .github, and other special directories
          for dir in */; do
            dir=${dir%/}
            if [[ "$dir" != ".git" && "$dir" != ".github" ]]; then
              echo "🔍 Checking $dir directory..."
              check_readme "$dir"
              check_root_links "$dir"
              echo "✅ $dir validation passed"
            fi
          done

          echo "🍮 All README.md files validated successfully!" 